/* eslint-disable no-unused-vars */
export enum FormIdsNameEnum {
  nature_of_work = 'nature_of_work',
  title = 'title',
  subtitle = 'subtitle',
  name= 'name',
  last_name= 'last_name',
  author_name2= 'author_name2',
  author_last_name2= 'author_last_name2',
  author_name3= 'author_name3',
  author_last_name3= 'author_last_name3',
  Advisor_name= 'Advisor_name',
  Advisor_last_name= 'Advisor_last_name',
  name_of_coadvisor1= 'name_of_coadvisor1',
  last_name_of_coadvisor1= 'last_name_of_coadvisor1',
  name_of_coadvisor2= 'name_of_coadvisor2',
  last_name_of_coadvisor2= 'last_name_of_coadvisor2',
  place_of_publication= 'place_of_publication',
  year_of_publication= 'year_of_publication',
  keywords1= 'keywords1',
  keywords2= 'keywords2',
  keywords3= 'keywords3',
  keywords4= 'keywords4',
  keywords5= 'keywords5',
}
