const CDU_CODES: { [key: string]: string } = {
  // 0 Generalidades. Informação. Organização.
  'Generalidades. Informação. Organização.': '0',
  'Ciência e técnica bibliográfica. Bibliografias. Catálogos.': '01',
  'Bibliotecas. Biblioteconomia.': '02',
  'Obras Gerais de Referência. Enciclopédias, Dicionários, etc.': '030',
  'Vaga': '040',
  'Publicações Periódicas. Periódicos. Função, Gestão Comercial e Editorial.': '050',
  'Organizações e outras formas de Cooperação. Instituições. Academias. Congressos. Sociedades. Organismos Científicos. Exposições. Museus.': '06',
  'Jornais. Jornalismo. Imprensa.': '070',
  'Poligrafias. Obras em Colaboração. Poligrafias Colectivas.': '08',
  'Manuscritos. Obras Notáveis e Obras Raras.': '09',

  // 1 Filosofia. Psicologia.
  'Filosofia. Psicologia.': '1',
  'Metafísica.': '11',
  'Metafísica Especial.': '122/129',
  'Filosofia da Mente e do Espírito. Metafísica da vida espiritual.': '13',
  'Sistemas e pontos de vista filosóficos.': '14',
  'Psicologia.': '159.9',
  'Lógica. Epistemologia. Teoria do Conhecimento. Metodologia da Lógica.': '16',
  'Filosofia Moral. Ética. Filosofia Prática': '17',

  // 2 Religião. Teologia
  'Religião. Teologia': '2',
  'Religiões Pré-históricas e Primitivas.': '21',
  'Religiões do Extremo Oriente. Taoísmo. Confucionismo. Religiões da Coreia e do Japão.': '22',
  'Religiões da Índia. Hinduísmo. Bramanismo. Vedismo, etc.': '23',
  'Budismo': '24',
  'Religiões do Mundo Antigo.': '25',
  'Judaísmo': '26',
  'Cristianismo. Igrejas e Denominações Cristãs.': '27',
  'Islamismo.': '28',
  'Movimentos Espirituais Modernos.': '29',

  // 3 Ciências Sociais. Economia. Direito. Política. Assistência Social. Educação.
  'Ciências Sociais. Economia. Direito. Política. Assistência Social. Educação.': '3',
  'Teorias, Metodologias e Métodos nas Ciências Sociais em Geral. Sociografia.': '30',
  'Métodos das Ciências Sociais': '303',
  'Estatística. Demografia. Sociologia.': '31',
  'Política.': '32',
  'Economia. Ciência Económica.': '33',
  'Direito. Jurisprudência.': '34',
  'Administração Pública. Assuntos Militares.': '35',
  'Protecção das Necessidades Materiais e Mentais da Vida. Serviço Social. Ajuda Social. Segurança Social. Habitação. Consumo. Seguros.': '36',
  'Educação.': '37',
  'Etnologia. Etnografia. Usos e Costumes. Tradições. Modo de Vida. Folclore': '39',

  // 4 Classe vaga. (não é utilizada)
  'Classe vaga. (não é utilizada)': '4',

  // 5 Matemática e Ciências Naturais.
  'Matemática e Ciências Naturais.': '5',
  'Generalidades sobre as Ciências Puras.': '50',
  'Ciência ambiental. Conservação dos Recursos Naturais. Ameaças ao Ambiente e Protecção Contra as Mesmas.': '502/504',
  'Matemática.': '51',
  'Astronomia. Astrofísica. Investigação Espacial. Geodesia.': '52',
  'Física.': '53',
  'Química. Mineralogia.': '54',
  'Ciências da Terra. Ciências Geológicas.': '55',
  'Paleontologia.': '56',
  'Ciências Biológicas no Geral. Antropologia.': '57',
  'Botânica.': '58',
  'Zoologia.': '59',

  // 6 Ciências Aplicadas. Medicina. Tecnologia.
  'Ciências Aplicadas. Medicina. Tecnologia.': '6',
  'Questões Gerais Referentes às Ciências Aplicadas.': '60',
  'Ciências Médicas.': '61',
  'Engenharia. Tecnologia em Geral.': '62',
  'Agricultura. Ciências Agrárias e Técnicas Relacionadas. Silvicultura. Explorações Agrícolas. Exploração da Vida Selvagem.': '63',
  'Economia Doméstica. Ciências Domésticas.': '64',
  'Gestão e Organização da Indústria, do Comércio e dos Transportes.': '65',
  'Tecnologia Química. Indústrias Químicas e Relacionadas.': '66',
  'Indústria Artes Industriais e Ofícios Diversos.': '67',
  'Indústrias, Artes e Ofícios e Comércio de Artigos Acabados ou Montados.': '68',
  'Indústria da Construção. Materiais para Construção. Procedimentos e Práticas de Construção.': '69',

  // 7 Arte. Belas-artes. Recreação. Diversões. Desportos.
  'Arte. Belas-artes. Recreação. Diversões. Desportos.': '7',
  'Artistas e sua obra.': '7 A/Z',
  'Teoria Geral da arte. Estética. Filosofia da arte. Crítica de arte, etc.': '7.01',
  'Planeamento territorial, Físico. Planeamento Regional, Urbano e Rural. Paisagens, Parques, Jardins, etc.': '71',
  'Arquitectura.': '72',
  'Artes Plásticas.': '73',
  'Desenho. Design. Artes e Ofícios Aplicados.': '74',
  'Pintura.': '75',
  'Artes Gráficas. Gravura.': '76',
  'Fotografia e Processos Similares': '77',
  'Música.': '78',
  'Divertimento. Espectáculos. Jogos. Desportos.': '79',

  // 8 Linguagem. Linguística. Literatura.
  'Linguagem. Linguística. Literatura.': '8',
  'Questões Gerais Referentes à Linguística e à Literatura. Filologia.': '80',
  'Linguística. Línguas.': '81',
  'Literatura.': '82',
  'Géneros Literários.': '82-1/-9',
  'Literatura de línguas individuais.': '821.1/.8',
  'Literatura em Línguas Germânicas.': '821.11',
  'Literatura Latina.': '821.124',
  'Literaturas em Línguas Românicas.': '821.13',
  'Literaturas Eslavas.': '821.16',
  'Literaturas Bálticas.': '821.17',
  'Literaturas Indicas.': '821.21',
  'Literaturas em Línguas Iranianas.': '821.22',
  'Literaturas em Línguas Semíticas.': '821.411',
  'Literaturas Árabes.': '821.411.21',
  'Literaturas Africanas em Línguas Bantu.': '821.432.8/.9',
  'Literaturas em Línguas Austronésias.': '821.62',
  'Literaturas Australianas.': '821.72',
  'Literaturas em Línguas dos Índios da América do Norte.': '821.81/82',
  'Literaturas em Línguas dos Índios da América do Sul e Central': '821.87',

  // 9 Geografia. Biografia. Historia.
  'Geografia. Biografia. Historia.': '9',
  'Arqueologia, Métodos e Técnicas para o Estudo das Civilizações e Culturas Passadas, Baseados na Descoberta e Interpretação de Vestígios, Materiais e Ruínas.': '902',
  'Pré-História. Vestígios Pré-Históricos. Artefactos. Antiguidades. Interpretação e Síntese de Relíquias Materiais do Homem Antigo, Suas Formas de Cultura e Civilizações.': '903',
  'Vestígios Culturais dos Períodos Históricos. Artefactos da História Antiga, Medieval e Moderna.': '904',
  'Monografias.': '908',
  'Geografia, Exploração da Terra e de Países. Viagens. Geografia Regional.': '91',
  'Biografias.': '929',
  'Biografias Individuais.': '929 A/Z',
  'História': '93/94',
  'Ciência da História. Historiografia': '93',
  'História em Geral.': '94',
  'História Individual dos Países.': '94(41/99)',
  'História da Europa.': '94(4)',
  'História do Oriente. História da Ásia.': '94(5)',
  'História da África.': '94(6)',
  'História das Américas (Norte, Central e Sul).': '94(7/8)',
  'História da América do Norte e América Central.': '94(7)',
  'História da América do Sul.': '94(8)',
  'História dos Estados e Regiões do Pacífico Sul e Austrália, Árctico e Antárctico.': '94(9)',
};

export function getCDUCode (descricao: string): string {
  return CDU_CODES[descricao] || 'Descrição não encontrada';
}
